export const ORDER_PRODUCTS_PROCESS = "ORDER_PRODUCTS_PROCESS";
export const ORDER_PRODUCTS_SUCCESS = "ORDER_PRODUCTS_SUCCESS";
export const ORDER_PRODUCTS_FAIL = "ORDER_PRODUCTS_FAIL";

export const MY_ORDER_PROCESS = "MY_ORDER_PROCESS";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";

export const ORDER_DETAILS_PROCESS = "ORDER_DETAILS_PROCESS";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const GET_ALL_ORDERS_PROCESS = "GET_ALL_ORDERS_PROCESS";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const DELETE_ORDER_PROCESS = "DELETE_ORDER_PROCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

export const UPDATE_ORDER_STATUS_PROCESS = "UPDATE_ORDER_STATUS_PROCESS";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";
export const UPDATE_ORDER_STATUS_RESET = "UPDATE_ORDER_STATUS_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
