export const ALL_PRODUCTS_PROCESS = "ALL_PRODUCTS_PROCESS";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_PROCESS = "GET_PRODUCT_DETAILS_PROCESS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO";

export const SUBMIT_REVIEW_PROCESS = "SUBMIT_REVIEW_PROCESS";
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAIL = "SUBMIT_REVIEW_FAIL";
export const SUBMIT_REVIEW_RESET = "SUBMIT_REVIEW_RESET";

export const ADMIN_ALLPRODUCT_PROCESS = "ADMIN_ALLPRODUCT_PROCESS";
export const ADMIN_ALLPRODUCT_SUCCESS = "ADMIN_ALLPRODUCT_SUCCESS";
export const ADMIN_ALLPRODUCT_FAIL = "ADMIN_ALLPRODUCT_FAIL";

export const CREATE_PRODUCT_PROCESS = "CREATE_PRODUCT_PROCESS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_PROCESS = "UPDATE_PRODUCT_PROCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const DELETE_PRODUCT_PROCESS = "DELETE_PRODUCT_PROCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const GET_SINGLE_PRODUCT_PROCESS = "GET_SINGLE_PRODUCT_PROCESS";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";

export const DELETE_REVIEW_PROCESS = "DELETE_REVIEW_PROCESS";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const GET_ALL_CART_ITEMS_SUCCESS = "GET_ALL_CART_ITEMS_SUCCESS";
export const GET_ALL_CART_ITEMS_PROCESS = "GET_ALL_CART_ITEMS_PROCESS";
export const GET_ALL_CART_ITEMS_FAIL = "GET_ALL_CART_ITEMS_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
