export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const REGISTER_PROCESS = "REGISTER_PROCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_USER_PROCESS = "LOAD_USER_PROCESS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const UPDATE_PROFILE_PROCESS = "UPDATE_PROFILE_PROCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const CHANGE_PASSWORD_PROCESS = "CHANGE_PASSWORD_PROCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const SEND_EMAIL_PROCESS = "SEND_EMAIL_PROCESS";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";

export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

export const FORGOT_PASSWORD_PROCESS = "FORGOT_PASSWORD_PROCESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORDL_FAIL";

export const GET_ALL_USERS_PROCESS = "GET_ALL_USERS_PROCESS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_SINGLE_USER_PROCESS = "GET_SINGLE_USER_PROCESS";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";

export const UPDATE_USER_STATUS_PROCESS = "UPDATE_USER_STATUS_PROCESS";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_FAIL = "UPDATE_USER_STATUS_FAIL";
export const UPDATE_USER_STATUS_RESET = "UPDATE_USER_STATUS_RESET";

export const CONTACTUS_PROCESS = "CONTACTUS_PROCESS";
export const CONTACTUS_SUCCESS = "CONTACTUS_SUCCESS";
export const CONTACTUS_FAIL = "CONTACTUS_FAIL";
export const CONTACTUS_RESET = "CONTACTUS_RESET";

export const DELETE_USER_PROCESS = "DELETE_USER_PROCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
